### ISSUE TITLE
listen servlet cannot handle memcache flush

### ISSUE THREAD

**Issue by davras** [davras/openhouseautomation#16]
make the servlet resilient to memcache flushes, if a memcache error occurs, return right away and let the client reconnect.

com.google.appengine.api.memcache.LogAndContinueErrorHandler handleServiceError: Service error in memcache
com.google.appengine.api.memcache.MemcacheServiceException: Memcache put: Set failed to set 1 keys: agpzfmdhdXRvYXJkchQLEgpDb250cm9sbGVyGIi48scNDA
	at com.google.appengine.api.memcache.AsyncMemcacheServiceImpl$8.transform(AsyncMemcacheServiceImpl.java:711)
	at com.google.appengine.api.memcache.AsyncMemcacheServiceImpl$8.transform(AsyncMemcacheServiceImpl.java:670)
	at com.google.appengine.api.memcache.MemcacheServiceApiHelper$RpcResponseHandler.convertResponse(MemcacheServiceApiHelper.java:57)
	at com.google.appengine.api.memcache.MemcacheServiceApiHelper$1.wrap(MemcacheServiceApiHelper.java:101)
	at com.google.appengine.api.memcache.MemcacheServiceApiHelper$1.wrap(MemcacheServiceApiHelper.java:96)
	at com.google.appengine.api.utils.FutureWrapper.wrapAndCache(FutureWrapper.java:55)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:92)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:88)
	at com.google.appengine.api.memcache.MemcacheServiceImpl.quietGet(MemcacheServiceImpl.java:26)
	at com.google.appengine.api.memcache.MemcacheServiceImpl.putAll(MemcacheServiceImpl.java:115)
	at com.googlecode.objectify.cache.KeyMemcacheService.putAll(KeyMemcacheService.java:91)
	at com.googlecode.objectify.cache.EntityMemcache.getAll(EntityMemcache.java:238)
	at com.googlecode.objectify.cache.CachingAsyncDatastoreService.get(CachingAsyncDatastoreService.java:252)
	at com.googlecode.objectify.impl.LoadEngine.fetch(LoadEngine.java:169)
	at com.googlecode.objectify.impl.Round.fetchPending(Round.java:160)
	at com.googlecode.objectify.impl.Round.execute(Round.java:137)
	at com.googlecode.objectify.impl.LoadEngine.execute(LoadEngine.java:92)
	at com.googlecode.objectify.impl.Round$1.nowUncached(Round.java:70)
	at com.googlecode.objectify.util.ResultCache.now(ResultCache.java:30)
	at com.googlecode.objectify.LoadResult.now(LoadResult.java:25)
	at com.openhouseautomation.ListenServlet.doLightsListen(ListenServlet.java:226)
	at com.openhouseautomation.ListenServlet.doPost(ListenServlet.java:166)

**Comment by davras** [comment]
I think it's fixed, but needs to be tested.
